export default {
    HOME: "/",
    ALLPETS: "/all-pets",
    ALLBREEDS: "/all-breeds",
    PETSDETAIL: "/pets-detail/:id",
    ADOPTIONFORM: "/adoption-form",
    STATUSREQUEST: "/adoption-request",
    ADOPTEDHISTORY: "/adopted-history",
    PETSHOP: "/shop",
    PRODUCTDETAIL: "/product/:id",
    SEARCHPAGE: "/search-page",
    ABOUTME: "/about-me",
    CATEGORYPET: "/category-pet",
    PETBYBREED: "/all-breeds/category/:category/:breed",
    BREEDBYCATEGORY: "/all-breeds/category/:category",
    PETCOLLECTION: "/pet-collection/:idCollection",
    SHOPPINGCART: "/cart",
    ADOPTIONFEECART: "/adoptcart",
    CARTPAYMENTLOADING: "/payment",
    ADOPTIONFEEPAYMENTLOADING: "/adoptpayment"
};
